/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    articles: Article;
    reports: Report;
    'job-openings': JobOpening;
    'product-items': ProductItem;
    'contact-submissions': ContactSubmission;
    'audit-log': AuditLog;
    users: User;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    reports: ReportsSelect<false> | ReportsSelect<true>;
    'job-openings': JobOpeningsSelect<false> | JobOpeningsSelect<true>;
    'product-items': ProductItemsSelect<false> | ProductItemsSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'audit-log': AuditLogSelect<false> | AuditLogSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('id' | 'en') | ('id' | 'en')[];
  globals: {};
  globalsSelect: {};
  locale: 'id' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * Used in the page address. Derived from title if left blank.
   */
  slug: string;
  excerpt?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  cover?: (number | null) | Media;
  author?: string | null;
  publishDate: string;
  /**
   * Shows in the Featured News list on the Newsroom page.
   */
  isFeatured?: boolean | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  /**
   * Seed content from the design. Replace before launch.
   */
  isSample?: boolean | null;
  /**
   * Editors submit for review. Only the Approver approves or rejects.
   */
  approvalStatus: 'draft' | 'in_review' | 'approved' | 'rejected';
  /**
   * Required when rejecting. The editor sees this.
   */
  rejectionReason?: string | null;
  submittedBy?: (number | null) | User;
  submittedAt?: string | null;
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describes the image for readers using a screen reader, and shows if the image fails to load.
   */
  alt: string;
  /**
   * Placeholder from the design. Replace before launch.
   */
  isSample?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * A user has exactly one role.
   */
  role: 'super_admin' | 'hr_admin' | 'news_admin' | 'marketing_admin' | 'sales_admin' | 'approver';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports".
 */
export interface Report {
  id: number;
  type: 'annual_report' | 'business_development';
  title: string;
  /**
   * Used in the page address. Derived from title if left blank.
   */
  slug: string;
  year: number;
  /**
   * Shown on the report card, left of the date.
   */
  author?: string | null;
  excerpt?: string | null;
  cover?: (number | null) | Media;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  financialTables?:
    | {
        /**
         * e.g. "Laporan Keuangan Posisi Keuangan 31 Desember 2025 (terlampir)".
         */
        intro?: string | null;
        /**
         * e.g. "LAPORAN LABA RUGI". Leave empty for none.
         */
        title?: string | null;
        caption?: string | null;
        rows?:
          | {
              label: string;
              value?: string | null;
              emphasis?: ('none' | 'label' | 'row') | null;
              gapBefore?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  publishDate?: string | null;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  /**
   * Seed content from the design. Replace before launch.
   */
  isSample?: boolean | null;
  /**
   * Editors submit for review. Only the Approver approves or rejects.
   */
  approvalStatus: 'draft' | 'in_review' | 'approved' | 'rejected';
  /**
   * Required when rejecting. The editor sees this.
   */
  rejectionReason?: string | null;
  submittedBy?: (number | null) | User;
  submittedAt?: string | null;
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-openings".
 */
export interface JobOpening {
  id: number;
  title: string;
  /**
   * Used in the page address. Derived from title if left blank.
   */
  slug: string;
  category: 'information-technology' | 'analysis-reporting' | 'sales-business-development';
  responsibilities?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  minimumQualifications?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  education?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * The "Lamar" button opens an email to this address.
   */
  applyEmail?: string | null;
  emailSubjectFormat?: string | null;
  /**
   * Only open positions are listed on the website.
   */
  isOpen?: boolean | null;
  postedDate?: string | null;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  /**
   * Seed content from the design. Replace before launch.
   */
  isSample?: boolean | null;
  /**
   * Editors submit for review. Only the Approver approves or rejects.
   */
  approvalStatus: 'draft' | 'in_review' | 'approved' | 'rejected';
  /**
   * Required when rejecting. The editor sees this.
   */
  rejectionReason?: string | null;
  submittedBy?: (number | null) | User;
  submittedAt?: string | null;
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-items".
 */
export interface ProductItem {
  id: number;
  name: string;
  category: 'credit-scoring' | 'analytics' | 'decisioning' | 'business-intelligence' | 'consulting';
  shortDescription?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  productStatus: 'live' | 'ready_to_sell';
  isNew?: boolean | null;
  features?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  suitableFor?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  useCases?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  /**
   * Seed content from the design. Replace before launch.
   */
  isSample?: boolean | null;
  /**
   * Editors submit for review. Only the Approver approves or rejects.
   */
  approvalStatus: 'draft' | 'in_review' | 'approved' | 'rejected';
  /**
   * Required when rejecting. The editor sees this.
   */
  rejectionReason?: string | null;
  submittedBy?: (number | null) | User;
  submittedAt?: string | null;
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  companyName: string;
  interestedIn:
    | 'Business Information'
    | 'Business Analytics'
    | 'Business Solutions'
    | 'Market Research'
    | 'CRIF PLUS Membership Programme'
    | 'Credit Bureau'
    | 'General Enquiries';
  hearAboutUs?:
    | (
        | 'Conference/Exhibition'
        | 'Flyer/Leaflet'
        | 'Google Search'
        | 'Magazine'
        | 'Referral'
        | 'Social Media'
        | 'Webinar'
        | 'Other'
      )
    | null;
  message?: string | null;
  consent: boolean;
  marketingChannels?: ('SMS/WhatsApp' | 'Telephone' | 'Email' | 'Newsletter')[] | null;
  marketingPreference?: ('opt_in' | 'opt_out') | null;
  locale?: string | null;
  pageUrl?: string | null;
  ipAddress?: string | null;
  userAgent?: string | null;
  consentTextVersion?: string | null;
  followedUp?: boolean | null;
  followedUpBy?: (number | null) | User;
  followedUpAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log".
 */
export interface AuditLog {
  id: number;
  action: string;
  collectionSlug?: string | null;
  documentId?: string | null;
  documentTitle?: string | null;
  user?: (number | null) | User;
  userEmail?: string | null;
  detail?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'reports';
        value: number | Report;
      } | null)
    | ({
        relationTo: 'job-openings';
        value: number | JobOpening;
      } | null)
    | ({
        relationTo: 'product-items';
        value: number | ProductItem;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'audit-log';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  body?: T;
  cover?: T;
  author?: T;
  publishDate?: T;
  isFeatured?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  isSample?: T;
  approvalStatus?: T;
  rejectionReason?: T;
  submittedBy?: T;
  submittedAt?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports_select".
 */
export interface ReportsSelect<T extends boolean = true> {
  type?: T;
  title?: T;
  slug?: T;
  year?: T;
  author?: T;
  excerpt?: T;
  cover?: T;
  body?: T;
  financialTables?:
    | T
    | {
        intro?: T;
        title?: T;
        caption?: T;
        rows?:
          | T
          | {
              label?: T;
              value?: T;
              emphasis?: T;
              gapBefore?: T;
              id?: T;
            };
        id?: T;
      };
  publishDate?: T;
  sortOrder?: T;
  isSample?: T;
  approvalStatus?: T;
  rejectionReason?: T;
  submittedBy?: T;
  submittedAt?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-openings_select".
 */
export interface JobOpeningsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  responsibilities?: T;
  minimumQualifications?: T;
  education?: T;
  applyEmail?: T;
  emailSubjectFormat?: T;
  isOpen?: T;
  postedDate?: T;
  sortOrder?: T;
  isSample?: T;
  approvalStatus?: T;
  rejectionReason?: T;
  submittedBy?: T;
  submittedAt?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-items_select".
 */
export interface ProductItemsSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  shortDescription?: T;
  description?: T;
  productStatus?: T;
  isNew?: T;
  features?:
    | T
    | {
        label?: T;
        id?: T;
      };
  suitableFor?:
    | T
    | {
        label?: T;
        id?: T;
      };
  useCases?:
    | T
    | {
        label?: T;
        id?: T;
      };
  sortOrder?: T;
  isSample?: T;
  approvalStatus?: T;
  rejectionReason?: T;
  submittedBy?: T;
  submittedAt?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  email?: T;
  phone?: T;
  companyName?: T;
  interestedIn?: T;
  hearAboutUs?: T;
  message?: T;
  consent?: T;
  marketingChannels?: T;
  marketingPreference?: T;
  locale?: T;
  pageUrl?: T;
  ipAddress?: T;
  userAgent?: T;
  consentTextVersion?: T;
  followedUp?: T;
  followedUpBy?: T;
  followedUpAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  action?: T;
  collectionSlug?: T;
  documentId?: T;
  documentTitle?: T;
  user?: T;
  userEmail?: T;
  detail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  isSample?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}